import { test, expect } from '@playwright/test';

test('roles, metadata correction, claims and administration', async ({ page }, testInfo) => {
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const login = async email => {
    await page.goto('/#/login');
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill('fixture demo password');
    await page.getByRole('button', { name: 'Login', exact: true }).last().click();
    await expect(page.getByRole('heading', { name: 'Discover your next task' })).toBeVisible();
  };
  const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(testInfo.project.use.viewport.width);
  await login('maintainer@civic.demo');
  await page.getByRole('button', { name: 'Manage issues', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Manage issues' })).toBeVisible();
  await page.getByRole('button', { name: 'Edit metadata' }).first().click();
  await page.getByLabel('Required skills (comma separated)').fill('Communication, Teamwork');
  await page.getByLabel('Civic topics (comma separated)').fill('Community support');
  await page.getByLabel('Estimated hours', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Save metadata' }).click();
  await expect(page.getByRole('status')).toContainText('Metadata updated');
  await noOverflow();
  await expect(page.getByRole('button', { name: 'Administration', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Sign out' }).click();
  await login('volunteer@civic.demo');
  await page.getByRole('button', { name: 'Claim task', exact: true }).first().click();
  await expect(page.getByRole('status').filter({ hasText: 'Task claimed' })).toContainText('Task claimed');
  await page.getByRole('button', { name: 'Participation', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Mark complete', exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Release task', exact: true }).click();
  await expect(page.getByText('No active claims.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Discover', exact: true }).click();
  await page.getByRole('button', { name: 'Claim task', exact: true }).first().click();
  await expect(page.getByRole('status').filter({ hasText: 'Task claimed' })).toContainText('Task claimed');
  await page.getByRole('button', { name: 'Participation', exact: true }).click();
  await page.getByRole('button', { name: 'Mark complete', exact: true }).click();
  await expect(page.locator('.historyList')).toContainText('completed');
  await noOverflow();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await login('administrator@civic.demo');
  await page.getByRole('button', { name: 'Administration', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Users and roles' })).toBeVisible();
  const volunteer = page.locator('.adminAccount').filter({ hasText: 'volunteer@civic.demo' });
  await volunteer.getByLabel('Maintainer', { exact: true }).check();
  await volunteer.getByLabel('community-care/civic-issues', { exact: true }).check();
  await volunteer.getByRole('button', { name: 'Save roles' }).click();
  await expect(page.getByRole('status')).toContainText('Changes saved');
  await volunteer.getByLabel('Maintainer', { exact: true }).uncheck();
  await volunteer.getByRole('button', { name: 'Save roles' }).click();
  await expect(page.getByRole('status')).toContainText('Changes saved');
  await expect(page.getByText('roles.assigned', { exact: true }).first()).toBeVisible();
  await noOverflow();
  await page.screenshot({ path: testInfo.outputPath('administration.png'), fullPage: true });
  expect(errors).toEqual([]);
});
