import { test, expect } from '@playwright/test';

test('volunteer account, profile, matching, details and saved list persist', async ({ page }, testInfo) => {
  const errors = [];
  const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(testInfo.project.use.viewport.width);
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Create your volunteer profile' }).click();
  await noOverflow();
  await page.getByLabel('Display name').fill('Civic Volunteer');
  await page.getByLabel('Email', { exact: true }).fill(`${testInfo.project.name}@example.com`);
  await page.getByLabel('Password', { exact: true }).fill('correct horse battery');
  await page.getByLabel('Confirm password', { exact: true }).fill('correct horse battery');
  await page.getByRole('button', { name: 'Register', exact: true }).last().click();
  await expect(page.getByRole('heading', { name: 'Discover your next task' })).toBeVisible();
  await page.getByRole('button', { name: 'My profile', exact: true }).click();
  await noOverflow();
  await page.getByLabel('Skills (comma separated)', { exact: true }).fill('Python');
  await page.getByLabel('Interests / civic topics (comma separated)').fill('Transportation');
  await page.getByLabel('Weekly availability (hours)').fill('3');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Profile saved');
  // Validation keeps previously entered profile fields.
  await page.getByLabel('Weekly availability (hours)').fill('-1');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.getByText('Enter availability between 0 and 168 hours.')).toBeVisible();
  await expect(page.getByLabel('Skills (comma separated)', { exact: true })).toHaveValue('Python');
  await page.getByLabel('Weekly availability (hours)').fill('3');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await page.getByRole('button', { name: 'Discover', exact: true }).click();
  await expect(page.getByText('100% match', { exact: true })).toBeVisible();
  await noOverflow();
  await page.getByLabel('Required skill', { exact: true }).fill('Python');
  await expect(page.getByText('1 matching tasks', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Improve Python transit API', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Improve Python transit API' })).toBeVisible();
  await noOverflow();
  await expect(page.getByRole('link', { name: 'Open source issue' })).toHaveAttribute('href', 'https://github.com/civic/transit/issues/1');
  await page.getByRole('button', { name: 'Save task', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Unsave task', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Saved tasks', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Improve Python transit API', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Improve Python transit API', exact: true })).toBeVisible();
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', testInfo.project.use.viewport.width);
  await page.screenshot({ path: testInfo.outputPath('saved-tasks.png'), fullPage: true });
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible();
  await page.getByLabel('Email', { exact: true }).fill(`${testInfo.project.name}@example.com`);
  await page.getByLabel('Password', { exact: true }).fill('correct horse battery');
  await page.getByRole('button', { name: 'Login', exact: true }).last().click();
  await expect(page.getByRole('heading', { name: 'Discover your next task' })).toBeVisible();
  await page.getByRole('button', { name: 'My profile', exact: true }).click();
  await expect(page.getByLabel('Skills (comma separated)', { exact: true })).toHaveValue('python');
  await page.getByRole('button', { name: 'Saved tasks', exact: true }).click();
  await page.getByRole('button', { name: 'Unsave task', exact: true }).click();
  await expect(page.getByText('Your shortlist starts here')).toBeVisible();
  expect(errors).toEqual([]);
});

test('create community issues in the demo repository and keep them after reload', async ({ page }, testInfo) => {
  await page.goto('/#/register');
  await page.getByLabel('Display name').fill('Task Creator');
  await page.getByLabel('Email', { exact: true }).fill(`creator-${testInfo.project.name}@example.com`);
  await page.getByLabel('Password', { exact: true }).fill('correct horse battery');
  await page.getByLabel('Confirm password', { exact: true }).fill('correct horse battery');
  await page.getByRole('button', { name: 'Register', exact: true }).last().click();
  await page.getByRole('button', { name: 'Create issue', exact: true }).click();
  await page.getByRole('region', { name: 'Create issue', exact: true }).getByRole('button', { name: 'Create issue', exact: true }).click();
  await expect(page.getByText('Enter at least two characters.')).toHaveCount(1);
  const title = `Community garden workday ${testInfo.project.name}`;
  await page.getByLabel('Issue title', { exact: true }).fill(title);
  await page.getByLabel('Description', { exact: true }).fill('Help neighbors plant vegetables in the shared community garden.');
  await page.getByLabel('Location (optional)', { exact: true }).fill('Maple Community Garden');
  await page.getByLabel('Required skills (comma separated)', { exact: true }).fill('Gardening, Teamwork');
  await page.getByLabel('Civic topic (optional)', { exact: true }).fill('Environment');
  await page.getByLabel('Estimated hours (optional)', { exact: true }).fill('4');
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(testInfo.project.use.viewport.width);
  await page.getByRole('region', { name: 'Create issue', exact: true }).getByRole('button', { name: 'Create issue', exact: true }).click();
  await expect(page.getByText('Issue created. It is now available in Discover and the demo repository.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: title, exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Repository', exact: true }).selectOption('community-care/civic-issues');
  await page.getByLabel('Search', { exact: true }).fill(title);
  await expect(page.getByText('1 matching tasks', { exact: true })).toBeVisible();
  await expect(page.getByText('Demo repository · Community Care / Civic Issues', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Repository', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Community Care / Civic Issues', exact: true })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Repository', exact: true })).toHaveValue('community-care/civic-issues');
  await page.getByLabel('Search', { exact: true }).fill(title);
  await expect(page.getByText('1 matching tasks', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: title, exact: true }).click();
  await expect(page.getByRole('link', { name: 'Open source issue' })).toHaveCount(0);
  await expect(page.getByText('📍 Maple Community Garden')).toBeVisible();
  await page.getByRole('button', { name: 'Save task', exact: true }).click();
  await page.getByRole('button', { name: 'Saved tasks', exact: true }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: title, exact: true })).toBeVisible();
});
