// Sample data shaped after the Civic Issue Matchmaker proposal (Section 2.1/2.4.1):
// each task is a normalized, authorized repository issue with a topic, required
// skills, difficulty, and estimated effort. Replace with a real API call to the
// Task Aggregation service once the backend is connected.

export const ISSUES = [
  { id: 1, title: "Fix address-autocomplete bug in benefits screener", topic: "Health & Human Services", org: "Code for America", repo: "codeforamerica/getcalfresh", difficulty: "Intermediate", effort: "Medium (4-10 hrs)", status: "Open", days: 2, claims: 3, desc: "The address field silently drops apartment numbers, causing eligibility checks to fail for multi-unit housing.", skills: ["JavaScript", "React", "API Integration"], url: "https://github.com/codeforamerica/getcalfresh" },
  { id: 2, title: "Add WCAG 2.1 alt-text audit to ballot lookup tool", topic: "Elections & Voting", org: "VoteAmerica", repo: "voteamerica/tool", difficulty: "Beginner", effort: "Small (1-3 hrs)", status: "Open", days: 1, claims: 5, desc: "Several polling-place images are missing alt text, which blocks screen-reader users from confirming their voting location.", skills: ["Accessibility (WCAG)", "HTML/CSS"], url: "https://github.com/voteamerica" },
  { id: 3, title: "Build GIS layer for flood-risk transit stops", topic: "Transportation", org: "18F", repo: "18f/transit-resilience", difficulty: "Advanced", effort: "Large (10+ hrs)", status: "Open", days: 6, claims: 2, desc: "Cross-reference FEMA flood zones with transit stop coordinates to flag at-risk stops for the planning team.", skills: ["GIS", "Python", "Data Analysis"], url: "https://github.com/18F" },
  { id: 4, title: "Write onboarding docs for new contributors", topic: "Government Transparency", org: "Chi Hack Night", repo: "chihacknight/data-portal", difficulty: "Beginner", effort: "Small (1-3 hrs)", status: "Open", days: 3, claims: 1, desc: "The open-data portal has no CONTRIBUTING.md; new volunteers don't know how to set up the local dev environment.", skills: ["Technical Writing", "Markdown"], url: "https://github.com/chihacknight" },
  { id: 5, title: "Add Spanish translation to eviction-notice explainer", topic: "Housing", org: "Bay Area Legal Aid Tech", repo: "balatech/eviction-explainer", difficulty: "Intermediate", effort: "Medium (4-10 hrs)", status: "Open", days: 4, claims: 0, desc: "Tenants need this legal-rights explainer in Spanish; the i18n scaffolding already exists, just missing translated strings.", skills: ["Translation", "React"], url: "https://github.com/balatech" },
  { id: 6, title: "Migrate 311 request API from XML to JSON", topic: "Public Safety", org: "NYC Planning Labs", repo: "nycplanninglabs/311-api", difficulty: "Advanced", effort: "Large (10+ hrs)", status: "Open", days: 8, claims: 4, desc: "Legacy XML responses are slowing down the mobile app; migrate the endpoint to JSON with backward-compatible versioning.", skills: ["Node.js", "API Integration", "DevOps"], url: "https://github.com/nycplanninglabs" },
  { id: 7, title: "Dashboard chart for tree-canopy coverage by zip code", topic: "Environment & Sustainability", org: "Code for America", repo: "codeforamerica/canopy-dashboard", difficulty: "Intermediate", effort: "Medium (4-10 hrs)", status: "Open", days: 5, claims: 2, desc: "Add a choropleth chart so residents can see canopy coverage trends in their own zip code over the last 5 years.", skills: ["React", "Data Analysis", "D3.js"], url: "https://github.com/codeforamerica" },
  { id: 8, title: "Unit tests for school-enrollment matching algorithm", topic: "Education & Civic Learning", org: "Bayes Impact", repo: "bayesimpact/enroll-match", difficulty: "Intermediate", effort: "Medium (4-10 hrs)", status: "Open", days: 3, claims: 1, desc: "The lottery-based enrollment matcher has no automated test coverage for edge cases like sibling priority.", skills: ["Python", "Testing"], url: "https://github.com/bayesimpact" },
  { id: 9, title: "Keyboard navigation for public-comment form", topic: "Government Transparency", org: "18F", repo: "18f/comment-portal", difficulty: "Beginner", effort: "Small (1-3 hrs)", status: "Claimed", days: 2, claims: 6, desc: "The comment submission form can't be completed using only a keyboard, blocking accessibility compliance.", skills: ["Accessibility (WCAG)", "JavaScript"], url: "https://github.com/18F" },
  { id: 10, title: "Rate-limit retry/backoff for permit-status scraper", topic: "Housing", org: "Chi Hack Night", repo: "chihacknight/permit-status", difficulty: "Advanced", effort: "Large (10+ hrs)", status: "Open", days: 7, claims: 1, desc: "The nightly scraper gets blocked by the city permitting site's rate limiter; needs exponential backoff and retry logic.", skills: ["Python", "DevOps"], url: "https://github.com/chihacknight" },
];

export const TOPICS = [...new Set(ISSUES.map((i) => i.topic))];
export const SKILLS = [...new Set(ISSUES.flatMap((i) => i.skills))].sort();
export const DIFFICULTIES = ["Beginner", "Intermediate", "Advanced"];
export const EFFORTS = ["Small (1-3 hrs)", "Medium (4-10 hrs)", "Large (10+ hrs)"];
export const DIFFICULTY_RANK = { Beginner: 1, Intermediate: 2, Advanced: 3 };
